De-engineering

diff --git a/greenhouse b/greenhouse
--- a/greenhouse
+++ b/greenhouse
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+# Switches
+LIGHT_SW=29
+WATER_SW=
+
+# Sensors
+WATER_RD=
+TEMP_RD=
+MOIST_RD=
+
 set -e
 
 if ! which gpio >/dev/null 2>&1; then
@@ -9,5 +18,25 @@ if ! which gpio >/dev/null 2>&1; then
 fi
 
 cd /opt/greenhouse
-. conf
-. functions
+
+
+function lights {
+    case "$0" in
+	on )
+	    gpio mode "$LIGHT_SW" out
+	    gpio write "$LIGHT_SW" 1
+	    ;;
+	off )
+	    gpio mode "$LIGHT_SW" out
+	    gpio write "$LIGHT_SW" 0
+	    ;;
+	read )
+	    gpio mode "$LIGHT_SW" in
+	    gpio read "$LIGHT_SW"
+	    ;;
+	* )
+	    echo "Error"
+	    exit 1
+	    ;;
+    esac
+}
